# GraphQL schema for no-manga.

scalar Time

type Manga {
  id: ID!
  name: String!
  otherNames: [String!]!,
  description: String!,
  demo: String!
  startDate: Time!,
  endDate: Time,
  genres: [String!]!,
  chapterCount: Int!
  chapterList: [Chapter!]!
  mangakaList: [Mangaka!]!
  magazineList: [Magazine!]!
}

type Chapter {
  id: String!
  chapterNum: Float!
  name: String,
  pageCount: Int!
  updatedAt: Time!
  manga: Manga!
}

type Mangaka {
  id: ID!
  name: String!
  otherNames: [String!]!
  description: String!
  job: String
  mangaList: [Manga!]!
}

type Magazine {
  id: ID!
  name: String!
  otherNames: [String!]!
  description: String!
  demo: String!
  mangaList: [Manga!]!
}

type Query {
  manga(ID: Int!): Manga
  mangaList: [Manga!]!

  chapter(mangaID: Int!, chapterNum: Float!): Chapter
  chapterList: [Chapter!]!

  mangaka(ID: Int!): Mangaka
  mangakaList: [Mangaka!]!

  magazine(ID: Int!): Magazine
  magazineList: [Magazine!]!
}
