config:
  target: "http://localhost:8080"
  phases:
    - duration: 15 # in seconds
      arrivalRate: 20 # + this many VU/sec
  processor: "./index.js"
scenarios:
  - name: "GraphQL Query load test"
    flow:
      - function: "testCases"
      - loop:
          - post:
              url: "/gql"
              json:
                query: "{{ $loopElement.query }}"
                variables: "{{ $loopElement.variables }}"
          # - log: "----------------------------------"
          # - log: "Sent a request to the {{ $loopElement.operation }}: {{ $loopElement.name }}"
          # - log: "And variables {{ $loopElement.variables }}"
        over: cases
