// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Magazine struct {
	ID          int      `json:"id"`
	Name        string   `json:"name"`
	OtherNames  []string `json:"otherNames"`
	Description string   `json:"description"`
	Demo        string   `json:"demo"`
	MangaList   []*Manga `json:"mangaList"`
}

type Mangaka struct {
	ID          int      `json:"id"`
	Name        string   `json:"name"`
	OtherNames  []string `json:"otherNames"`
	Description string   `json:"description"`
	MangaList   []*Manga `json:"mangaList"`
}

type SeriesMangaka struct {
	ID          int      `json:"id"`
	Name        string   `json:"name"`
	OtherNames  []string `json:"otherNames"`
	Description string   `json:"description"`
	Job         string   `json:"job"`
	MangaList   []*Manga `json:"mangaList"`
}
